#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# get architecture
case "$(uname -m)" in
    i686)
        arch=i386;;
    *)
        arch="$(uname -m)";;
esac

cd "$script_dir"

app_pathname="$(find -name "herb*${arch}*" | sort -V | tail -n 1)"
app_path="$(dirname "$app_pathname")"
app_name="$(basename "$app_pathname")"

cd "$app_path"
chmod +x "$app_name"
"./$app_name"
